### ISSUE TITLE
curve type is incorrect

### ISSUE THREAD

**Issue by NewFarmer21** [singular-labs/Singular-SKAdNetwork-App#12]
Apple update the document to user prime256v1，so we need to update the skadnetwork-server.

**Comment by yetnelson** [comment]
hi @NewFarmer21, I also find this problem. and try to update to "CURVE = fe_curve.P256" in skadnetwork-server/ecdsa_wrapper.py. But still can't receive postback.

Did you receive postback from SKAdNetwork successful?

**Comment by shefdanny** [comment]
fixed
