### ISSUE TITLE
No iOS 14 availability check

### ISSUE THREAD

**Issue by manelizzard** [singular-labs/Singular-SKAdNetwork-App#3]
Won't this crash on earlier iOS versions?

https://github.com/singular-labs/Singular-SKAdNetwork-App/blob/774b1f63d1e4e81b8fd75b74f487f9008188dac0/advertiser-sample-app/SingularAdvertiserSampleApp/ViewController.m#L30

**Comment by danielxt** [comment]
Hi @manelizzard - good point, thanks, we'll add a check around that as well
