### ISSUE TITLE
genkey

### ISSUE THREAD

**Issue by zhangchark** [singular-labs/Singular-SKAdNetwork-App#7]
Hi guys, you save my days, thank you so much;
Could you share **how you generate the ecdsa key with pkcs8**?
here is my way, but not work when run 'get_skadnetwork_parameters.py':

`openssl ecparam -genkey -name secp256r1 -out ecdsa_private_key.pem`
`openssl pkcs8 -topk8 -inform PEM -in ecdsa_private_key.pem -outform PEM -nocrypt -out key.pem`
`openssl  ec -in ecdsa_private_key.pem -out ecdsa_public_key.pem -pubout`

**Comment by zhangchark** [comment]
well，i found apple had renew  their doc,and give the code `openssl ecparam -name prime192v1 -genkey -noout -out companyname_skadnetwork_private_key.pem
`

the 'get_skadnetwork_parameters.py' worked with the key that generated as apple`s code.

**Comment by danielxt** [comment]
Hi @zhangchark - thanks! glad this helped :)

And thanks for the comment - we will add this to the README
